config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get	 '/signup',    to: 'teachers#new'
  get	 '/login',	   to: 'sessions#new'
  get	 '/list',	   to: 'teachers#index'
  post	 '/login',	   to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  resources :teachers, :quizzes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :teacher
  validates :teacher_id, presence: true
  validates :name, presence: true
  validates :description, presence: true
  has_many :questions, dependent: :destroy
end

app/models/teacher.rb
class Teacher < ApplicationRecord
	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates(:email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false })
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
	has_many :quizzes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def require_login
      unless logged_in?
        flash[:warning] = "Debe iniciar sesion con sus credenciales!"
        redirect_to root_path
      end
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    # @quizzes = Quiz.all
    @quizzes = current_teacher.quizzes
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = current_teacher.quizzes.build if logged_in?
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    # @quiz = Quiz.new(quiz_params)
    @quiz = current_teacher.quizzes.build(quiz_params)

    if @quiz.save
      flash[:success] = "Quiz creado!"
      redirect_to quizzes_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:name, :description, :teacher_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	teacher = Teacher.find_by(email: params[:session][:email].downcase)
  	if teacher && teacher.authenticate(params[:session][:password])
  		log_in teacher
  		redirect_to quizzes_path
  	else
  		flash[:danger] = 'Combinacion incorrecta de correo/contrasena'
  		render 'new'
  	end 
  end

  def destroy
  	log_out
  	redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :require_login, only: [:show, :edit, :update, :destroys]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      flash[:success] = "Usuario creado exitosamente. Bienvenido a Thinker!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(teacher)
  	session[:teacher_id] = teacher.id
	end

	def log_out
    session.delete(:teacher_id)
    @current_teacher = nil
  end

	def current_teacher
  	@current_teacher ||= Teacher.find_by(id: session[:teacher_id])
	end

	def logged_in?
	 !current_teacher.nil?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewThinker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if logged_in? %>
  		<%= link_to 'Log out', logout_path, method: :delete, data: { confirm: 'Esta seguro?' } %>
	    <%= yield %>
	<% else %>
		<%= yield %>
	<% end %>
  </body>
</html>

app/views/quizzes/_form.html.erb
<%= form_for(quiz) do |f| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: "Descripcion..." %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.name %></td>
        <td><%= quiz.description %></td>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>Quiz Nuevo</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>
<% flash.each do |message_type, message| %>
	<div class="alert alert-<%= message_type %> fade in"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times</a><%= message %></div>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @quiz.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @quiz.description %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @quiz.teacher %>
</p>

<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>

app/views/static_pages/home.html.erb
<% flash.each do |message_type, message| %>
	<div class="alert alert-<%= message_type %> fade in"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times</a><%= message %></div>
<% end %>
<section class="container-fluid">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
		<%= image_tag("thinker.png", alt: "Thinker ESPOL", class: "img-responsive center-block imgpad") %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-2 col-md-offset-4">
			<%= link_to "Log in", login_path, class: "btn btn-lg btn-primary center-block" %>
		</div>
		<div class="col-md-2">
			<%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary center-block" %>
		</div>
	</div>
</section>

app/views/teachers/_form.html.erb
<%= form_for(teacher) do |f| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <h2><%= pluralize(teacher.errors.count, "error") %> al registrar usuario</h2>

        <ul>
        <% teacher.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.email %></td>
        <td><%= teacher.password %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/teachers/new.html.erb
<h1>Registro de Usuario</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', root_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @teacher.password %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>